### PR TITLE
Add bar component

### PR DESCRIPTION
**Pull request by josiahwiebe**
Hey @saisandeepvaddi, this PR just adds the Bar component for feature parity with Sara Vieira's [styled-loaders](https://github.com/SaraVieira/styled-loaders).

### CODE REVIEW

**Comment by saisandeepvaddi** [comment]
Awesome. I'll check this PR later tonight or tomorrow.
Thanks for contribution :)

**Comment by saisandeepvaddi** [comment]
Looks good. I think we should add `Bar` to main `README.md`.
Can you please update README as well?

**Comment by josiahwiebe** [comment]
I've added a description and GIF to the `README.md` file

**Comment by saisandeepvaddi** [comment]
@josiahwiebe 

Published update to npm. 
Thanks a lot for contribution :) 🙏  💯

**Pull request merged**
